name: Teardown
description: Teardown

inputs:
  set-temp:
    description: Set the temp files?
    default: "true"
  set-data:
    description: Set the interim DB?
    default: "true"

runs:
  using: composite
  steps:
    - name: Save Cached Temp
      uses: actions/cache/save@v4.2.2
      continue-on-error: true
      if: ${{ inputs.set-temp == 'true' }}
      with:
        path: temp
        key: temp-${{ github.run_id }}-${{ github.job }}
        enableCrossOsArchive: true
    - name: Save Cached DB
      uses: actions/cache/save@v4.2.2
      continue-on-error: true
      if: ${{ inputs.set-data == 'true' }}
      with:
        path: data
        key: data-${{ github.run_id }}-${{ github.job }}
        enableCrossOsArchive: true
