name: Yugipedia Import
description: Yugipedia Import

inputs:
  i:
    description: The part.
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
    - name: Run YGOJSON (Yugipedia ${{inputs.i}})
      shell: bash
      run: |
        ygojson --production --no-ygoprodeck --no-yamlyugi --yugipedia-use-partition temp/part${{inputs.i}}.json --no-manual --individuals '' --no-individuals
    - name: Teardown
      uses: ./.github/actions/teardown
      if: always()
