name: Generate/Upload Database

on:
  workflow_dispatch:
#   schedule:
#    - cron: 0 0 * * *

permissions:
  contents: write
  actions: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          get-temp: false
          get-data: false
      - name: Lint
        run: |
          pre-commit run --all-files
  pre-yugipedia:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          get-data: false
      - name: Run YGOJSON (Pre-Yugipedia)
        run: |
          ygojson --production --download --yugipedia-gen-partitions 8 --yugipedia-gen-partitions-prefix temp/part --no-manual --individuals '' --no-individuals
      - name: Teardown
        uses: ./.github/actions/teardown
        if: always()
  yugipedia-1:
    runs-on: ubuntu-latest
    needs: pre-yugipedia
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 1)
        uses: ./.github/actions/yugipedia
        with:
          i: 1
  yugipedia-2:
    runs-on: ubuntu-latest
    needs: yugipedia-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 2)
        uses: ./.github/actions/yugipedia
        with:
          i: 2
  yugipedia-3:
    runs-on: ubuntu-latest
    needs: yugipedia-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 3)
        uses: ./.github/actions/yugipedia
        with:
          i: 3
  yugipedia-4:
    runs-on: ubuntu-latest
    needs: yugipedia-3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 4)
        uses: ./.github/actions/yugipedia
        with:
          i: 4
  yugipedia-5:
    runs-on: ubuntu-latest
    needs: yugipedia-4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 5)
        uses: ./.github/actions/yugipedia
        with:
          i: 5
  yugipedia-6:
    runs-on: ubuntu-latest
    needs: yugipedia-5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 6)
        uses: ./.github/actions/yugipedia
        with:
          i: 6
  yugipedia-7:
    runs-on: ubuntu-latest
    needs: yugipedia-6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 7)
        uses: ./.github/actions/yugipedia
        with:
          i: 7
  yugipedia-8:
    runs-on: ubuntu-latest
    needs: yugipedia-7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run YGOJSON (Yugipedia 8)
        uses: ./.github/actions/yugipedia
        with:
          i: 8
  post-yugipedia:
    runs-on: ubuntu-latest
    needs: yugipedia-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run YGOJSON (Post-Yugipedia)
        run: |
          ygojson --production --no-ygoprodeck --no-yamlyugi --no-yugipedia
      - name: Test
        run: |
          python test/validate_data.py
      - name: Push Individuals
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: v1/individual # update this when we have new schema versions
          FOLDER: data/individual
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
      - name: Push Aggregates
        uses: s0/git-publish-subdir-action@v2.6.0
        continue-on-error: true # TODO: files too big; we need to enable git-lfs to remove this line
        env:
          REPO: self
          BRANCH: v1/aggregate # update this when we have new schema versions
          FOLDER: data/aggregate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
      - name: Archive Individuals
        uses: vimtor/action-zip@v1.2
        with:
          files: data/individual
          dest: individual.zip
      - name: Archive Aggregates
        uses: vimtor/action-zip@v1.2
        with:
          files: data/aggregate
          dest: aggregate.zip
      - name: Get Latest Release
        id: latest_release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove Old Individuals ZIP
        uses: flcdrg/remove-release-asset-action@v4.0.4
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.latest_release.outputs.id }}
          asset_name: individual.zip
      - name: Remove Old Aggregates ZIP
        uses: flcdrg/remove-release-asset-action@v4.0.4
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.latest_release.outputs.id }}
          asset_name: aggregate.zip
      - name: Upload Individuals ZIP
        uses: csexton/release-asset-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.latest_release.outputs.upload_url }}
          file: individual.zip
      - name: Upload Aggregates ZIP
        uses: csexton/release-asset-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.latest_release.outputs.upload_url }}
          file: aggregate.zip
      - name: Teardown
        uses: ./.github/actions/teardown
        if: always()
        with:
          set-data: false
