name: Generate/Upload Database

on:
  workflow_dispatch:
#   schedule:
#    - cron: 0 0 * * *

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Restore Cached Temp
      uses: actions/cache/restore@v4.0.2
      continue-on-error: true
      with:
        path: temp
        key: temp
        restore-keys: |
          temp-
        enableCrossOsArchive: true
    - name: Install YGOJSON
      run: |
        python -m pip install -e .[dev,test]
    - name: Lint
      run: |
        pre-commit run --all-files
    - name: Run YGOJSON
      run: |
        ygojson --download --production
    - name: Test
      run: |
        python test/validate_data.py
    - name: Save Cached Temp
      uses: actions/cache/save@v4.0.2
      continue-on-error: true
      if: always()
      with:
        path: temp
        key: temp-${{ github.run_id }}
        enableCrossOsArchive: true
    - name: Push Individuals
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: self
        BRANCH: v1/individual # update this when we have new schema versions
        FOLDER: data/individual
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
    - name: Push Aggregates
      uses: s0/git-publish-subdir-action@v2.6.0
      continue-on-error: true # TODO: files too big; we need to enable git-lfs to remove this line
      env:
        REPO: self
        BRANCH: v1/aggregate  # update this when we have new schema versions
        FOLDER: data/aggregate
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
    - name: Archive Individuals
      uses: vimtor/action-zip@v1.2
      with:
        files: data/individual
        dest: individual.zip
    - name: Archive Aggregates
      uses: vimtor/action-zip@v1.2
      with:
        files: data/aggregate
        dest: aggregate.zip
    - name: Get Latest Release
      id: latest_release
      uses: gregziegan/fetch-latest-release@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Remove Old Individuals ZIP
      uses: flcdrg/remove-release-asset-action@v4.0.4
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.latest_release.outputs.id }}
        asset_name: individual.zip
    - name: Remove Old Aggregates ZIP
      uses: flcdrg/remove-release-asset-action@v4.0.4
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.latest_release.outputs.id }}
        asset_name: aggregate.zip
    - name: Upload Individuals ZIP
      uses: csexton/release-asset-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.latest_release.outputs.upload_url }}
        file: individual.zip
    - name: Upload Aggregates ZIP
      uses: csexton/release-asset-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.latest_release.outputs.upload_url }}
        file: aggregate.zip
