name: Yugipedia Import

on:
  workflow_call:
    inputs:
      i:
        type: number
        required: true

jobs:
  yugipedia:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Run YGOJSON (Yugipedia ${{inputs.i}})
        run: |
          ygojson --production --no-ygoprodeck --no-yamlyugi --yugipedia-use-partition temp/part${{inputs.i}}.json --no-manual --individuals '' --no-individuals
      - name: Teardown
        uses: ./.github/workflows/teardown.yml
        if: always()
